trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self  # Asegura que se descargue el código
  - script: echo "Pipeline ejecutándose correctamente"
