trigger:
  branches:
    include:
      - main  # Cambia esto si usas otra rama principal

pool:
  vmImage: 'ubuntu-latest'  # Usa Windows si necesitas herramientas específicas de Windows

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: 'Instalar .NET 8 SDK'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      dotnet restore
    displayName: 'Restaurar dependencias'

  - script: |
      dotnet build --configuration $(buildConfiguration) --no-restore
    displayName: 'Compilar aplicación'

  - script: |
      dotnet test --configuration $(buildConfiguration) --no-build --verbosity normal
    displayName: 'Ejecutar pruebas'

  - script: |
      dotnet publish -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
    displayName: 'Publicar aplicación'

  - task: PublishBuildArtifacts@1
    displayName: 'Publicar artefactos'
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: 'drop'
